# Hexo Configuration
## Site
title: pduchnovsky | a drop in the ocean | DevOps engineer on the loose
description: "Programming, System Administration & Photography Blog & Portfolio"
keywords: programming system administration photography portfolio sysadmin devops engineer
author: Peter Duchnovsky
## URL
url: https://pduchnovsky.com
root: /
permalink: :year/:month/:day/:title/
pretty_urls:
  trailing_index: true
  trailing_html: true
## Directory
source_dir: source
public_dir: public
archive_dir: archives
i18n_dir: :lang
## Writing
new_post_name: :title.md
default_layout: post
titlecase: true
external_link:
  enable: true
  field: site
  exclude: ""
filename_case: 0
render_drafts: false
relative_link: false
future: true
prismjs:
  enable: true
  preprocess: true
  line_number: true
  tab_replace: ""
## Home page setting
index_generator:
  path: ""
  per_page: 10
  order_by: -date
# Metadata elements
meta_generator: true
# Date / Time format
date_format: YYYY-MM-DD
time_format: HH:mm:ss
updated_option: "mtime"
# Pagination
per_page: 10
pagination_dir: page
# Theme:
theme: minima
## Extensions
## Netlify CMS
include: _redirects
skip_render: admin/*
# hexo-all-minifier
all_minifier: true
image_minifier:
  optimizationLevel: 2
  progressive: true
# hexo-generator-sitemap
sitemap:
  path: /sitemap.xml
  template: ./sitemap_template.xml
  rel: true
  tags: true
  categories: true
