baseURL = "https://duchnovsky.com"
title = "duchnovsky.com"
theme = "hugo-coder"
languageCode = "en"
defaultContentLanguage = "en"
pygmentsUseClasses = true
enableEmoji = true
enableRobotsTXT = true
buildFuture = true
buildExpired = true

[pagination]
pagerSize = 5

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[markup.highlight]
noClasses = false

[privacy.instagram]
simple = true
[privacy.x]
enableDNT = true
simple = true
[privacy.vimeo]
enableDNT = true
simple = true
[privacy.youtube]
privacyEnhanced = true

[permalinks]
posts = "/:year/:month/:slug/"

[params]
author = "Peter Duchnovsky"
license = '<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA-4.0</a>'
description = "#IaC, #coding, #devops, #automation, #homelab, #security, #multicloud, #infrastructure & #photography => Blog/Portfolio"
keywords = "multicloud,cloud,homelab,programming,coding,system,administration,photography,portfolio,sysadmin,devops,engineer,engineering"
info = "Site Reliability Engineer"
gravatar = "peterduchnovsky@gmail.com"
footerContent = "“Trust Me ❤ I'm An Engineer”"
dateFormat = "January 2, 2006"
hideFooter = false
hideCredits = true
hideCopyright = false
since = 2020
enablePostImg = true
enablePostSummary = true
images = ["/thumb.png"]
rtl = false
colorScheme = "auto"
hideColorSchemeToggle = false
maxSeeAlsoItems = 5
enableTwemoji = false

[params.utterances]
repo = "pduchnovsky/duchnovsky.com"
issueTerm = "pathname"
label = "comment"
theme = "preferred-color-scheme"

[params.csp]
childsrc = ["'self'"]
fontsrc = ["'self'"]
formaction = ["'self'"]
framesrc = ["'self'", "https://utteranc.es"]
imgsrc = ["'self'", "https://www.gravatar.com"]
objectsrc = ["'none'"]
stylesrc = ["'self'", "'unsafe-inline'"]
scriptsrc = ["'self'", "'unsafe-inline'", "https://utteranc.es"]
prefetchsrc = ["'self'"]
connectsrc = ["'self'"]

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 1
url = "https://linkedin.com/in/pduchnovsky"
[[params.social]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 4
url = "https://github.com/pduchnovsky"

[languages.en]
languageName = "🇺🇸"

[[languages.en.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.en.menu.main]]
name = "Photography"
weight = 2
url = "portfolio/"

[[languages.en.menu.main]]
name = "HomeLab"
weight = 3
url = "homelab/"

[[languages.en.menu.main]]
name = "About me"
weight = 4
url = "about-me/"

[[languages.en.menu.main]]
name = "Email"
weight = 5
url = "mailto:peter@duchnovsky.com"

[languages.sk]
languageName = "🇸🇰"

[languages.sk.params]
author = "Peter Duchnovský"
info = "Site Reliability Engineer"
description = "#IaC, #coding, #devops, #automation, #homelab, #security, #multicloud, #infrastructure & #photography => Blog/Portfolio"
keywords = "multicloud,cloud,homelab,programovanie,kódovanie,systém,administrácia,fotografovanie,portfólio,sysadmin,devops,inžinier,inžinierstvo"
dateFormat = "2. January, 2006"

[[languages.sk.menu.main]]
name = "Blog"
weight = 1
url = "posts/"

[[languages.sk.menu.main]]
name = "Fotografia"
weight = 2
url = "portfolio/"

[[languages.sk.menu.main]]
name = "Laboratórium"
weight = 3
url = "laboratorium/"

[[languages.sk.menu.main]]
name = "O mne"
weight = 4
url = "o-mne/"

[[languages.sk.menu.main]]
name = "Email"
weight = 5
url = "mailto:admin@duchnovsky.com"
