backend:
  name: git-gateway
  branch: main
display_url: https://pduchnovsky.com
media_folder: "source/images"
public_folder: "/images"

collections:
  - name: "posts"
    label: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", required: true, widget: "datetime"}
      - {label: "Edited Date", name: "updated", required: true, widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", required: true, widget: "image"}
      - {label: "Categories", name: "category", required: false, widget: "list"}
      - {label: "Tags", name: "tags", required: false, widget: "list"}
      - {label: "Keywords", name: "keywords", required: false, widget: "list"}
      - {label: "Body", name: "body", widget: "markdown"}
