backend:
  name: git-gateway
  branch: main
display_url: https://pduchnovsky.com
media_folder: "source/images"
public_folder: "/images"
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Post"
    folder: "source/_posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", required: true, widget: "datetime", date_format: "YYYY-MM-DD", time_format: "HH:mm:ss"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
