site_url: https://duchnovsky.com
#local_backend: true
backend:
  name: github
  repo: pduchnovsky/duchnovsky.com
  branch: main
  base_url: https://github-oauth.duchnovsky.com
media_folder: "assets/images" # This is where images uploaded via CMS will go
public_folder: "images" # This is the public URL path for those images
i18n:
  structure: multiple_files
  locales: [en, sk]
  default_locale: en
collections:
  - name: "posts"
    label: "Posts"
    i18n: true
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "toml-frontmatter"
    extension: "md"
    fields:
      - { name: "title", label: "Title", widget: "string", i18n: true }
      - {
          name: "description",
          label: "Description",
          widget: "text",
          i18n: true,
        }
      - { name: "date", label: "Date", widget: "datetime", i18n: true }
      - { name: "slug", label: "Slug", widget: "string", i18n: true }
      - {
          name: "images",
          label: "Images",
          widget: "list",
          field: { name: "image", label: "Image", widget: "image" },
          i18n: true,
        }
      - { name: "categories", label: "Categories", widget: "list", i18n: true }
      - { name: "tags", label: "Tags", widget: "list", i18n: true }
      - {
          name: "series",
          label: "Series",
          widget: "list",
          required: false,
          i18n: true,
        }
      - label: "Body"
        name: "body"
        widget: "markdown"
        i18n: true
        editor_components:
          - "image"
          - "code-block"
          - "notice"
  - name: "external_links"
    label: "External Links"
    i18n: true
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    format: "toml-frontmatter"
    extension: "md"
    fields:
      - { name: "title", label: "Title", widget: "string", i18n: true }
      - { name: "date", label: "Date", widget: "datetime", i18n: true }
      - { name: "slug", label: "Slug", widget: "string", i18n: true }
      - { name: "tags", label: "Tags", widget: "list", i18n: true }
      - {
          name: "images",
          label: "Images",
          widget: "list",
          field: { name: "image", label: "Image", widget: "image" },
          i18n: true,
        }
      - {
          name: "externalLink",
          label: "External Link",
          widget: "string",
          required: false,
          i18n: true,
        }
  - name: "pages"
    label: "Pages"
    i18n: true
    folder: "content"
    create: true
    slug: "{{slug}}"
    format: "toml-frontmatter"
    extension: "md"
    fields:
      - { name: "title", label: "Title", widget: "string", i18n: true }
      - {
          name: "description",
          label: "Description",
          widget: "text",
          i18n: true,
        }
      - { name: "slug", label: "Slug", widget: "string", i18n: true }
      - {
          name: "images",
          label: "Images",
          widget: "list",
          field: { name: "image", label: "Image", widget: "image" },
          required: false,
          i18n: true,
        }
      - label: "Body"
        name: "body"
        widget: "markdown"
        i18n: true
        editor_components:
          - "image"
          - "code-block"
          - "notice"
